dist: trusty
sudo: required
cache: ccache

language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - libstdc++6
      - libblas-dev
      - liblapack-dev
      - python-setuptools
      - libgif-dev
      - vim-common
      - libx11-dev

env:
  global:
    - CI=false
    - OMP_NUM_THREADS=4
    - CC=gcc-5
    - CXX=g++-5

script:
  # Let's see the current ccache status
  # We should have a primed cache already (from master builds)
  - ccache -s

  # We sometimes get `error: No space left on device`
  # The workaround seems to be to force blocking I/O
  # See https://github.com/travis-ci/travis-ci/issues/8902 and
  # https://github.com/travis-ci/travis-ci/issues/4704#issuecomment-348435959
  # Check whether O_NONBLOCK is set (probably should print "1"):
  - python -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); print(flags&os.O_NONBLOCK);'
  # Turn off O_NONBLOCK:
  - python -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); fcntl.fcntl(sys.stdout, fcntl.F_SETFL, flags&~os.O_NONBLOCK);'
  # Check whether O_NONBLOCK is set (should print "0"):
  - python -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); print(flags&os.O_NONBLOCK);'

  # Remove style transfer unit test due to out-of-memory error.
  # Remove some additional tests temporarily to get under the two-hour timeout.
  - rm src/unity/python/turicreate/test/test_style_transfer.py src/unity/python/turicreate/test/test_object_detector.py

  # Build the wheel
  - bash scripts/make_wheel.sh --build_number=$CI_PIPELINE_ID --num_procs=3 --debug --skip_cpp_test --skip_doc

  # Let's see the current ccache status again
  # We should have more in the cache (and maybe some cache hits)
  - ccache -s
